import { Box, Container } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
                <body className={inter.className}>
                    <Container maxWidth="xl" sx={{height:'100vh'}} >
                        <Box sx={{ height: '100vh' }} >
                            {children}
                        </Box>
                    </Container>
                </body>
        </html>
  )
}
